### PR TITLE
Add simple reshuffle button

### PR DESCRIPTION
**Pull request by matiassingers**
Wrap loops in functions and make it possible to reshuffle the whole board.

Adds a simple reshuffle button: 

screen shot 2014-05-22 at 11 16 25

### CODE REVIEW

**Comment by staringispolite** [comment]
Some issues with this PR: it operates on anchor tags still, and doesn't reset the 'selected' tags in each square when you get a new card, both of which I've fixed.

I also think it might accidentally get clicked... but it's a small enough button, and this is a useful/cool enough feature, that it's worth seeing if anyone complains.

**Comment by matiassingers** [comment]
@staringispolite do you want me to rebase this PR to get your changes in?

**Comment by staringispolite** [comment]
Added my changes, and pushed this live.

**Comment by matiassingers** [comment]
@staringispolite awesome! :tada:

**Pull request merged**
